permalink: pretty

theme: jekyll_patternbot
patternbot:
  title: "Laniel Design"
  description: |
    A Portfolio website for graphic designer Kayleigh Laniel, detailing her work  with highlighted interests in Illustration and graphics for print.
  font_url: "https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i|Ubuntu&display=swap"
  colors:
    background: "--color-primary-light"
    accent: "--color-primary-dark"
  patterns:
    brand.logos: "--color-neutral"
