title: "Footers"
description: |
  Footers should be used in situations where a subtle nod to the company is needed.they should be placed at the bottom of the page, after all of the content has been placed
