title: "Headers"
description: |
  Headers should be used in situations where a reminder and a welcomeing view to the company is needed.they should be placed at the top of the page, before all of the content has been placed
